# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddEditCoffeeForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.roastLineEdit.setObjectName("roastLineEdit")
        self.verticalLayout.addWidget(self.roastLineEdit)
        self.grindLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.grindLineEdit.setObjectName("grindLineEdit")
        self.verticalLayout.addWidget(self.grindLineEdit)
        self.descriptionLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.descriptionLineEdit.setObjectName("descriptionLineEdit")
        self.verticalLayout.addWidget(self.descriptionLineEdit)
        self.priceLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.priceLineEdit.setObjectName("priceLineEdit")
        self.verticalLayout.addWidget(self.priceLineEdit)
        self.volumeLineEdit = QtWidgets.QLineEdit(AddEditCoffeeForm)
        self.volumeLineEdit.setObjectName("volumeLineEdit")
        self.verticalLayout.addWidget(self.volumeLineEdit)
        self.saveButton = QtWidgets.QPushButton(AddEditCoffeeForm)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout.addWidget(self.saveButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Редактировать кофе"))
        self.nameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Название сорта"))
        self.roastLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Степень обжарки"))
        self.grindLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Молотый/в зернах"))
        self.descriptionLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание вкуса"))
        self.priceLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Цена"))
        self.volumeLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Объем упаковки"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Сохранить"))

